version: '3'
services:

  db:
    build: ./postgres
    environment:
      POSTGRES_USER: lumen
      POSTGRES_PASSWORD: secret
    networks:
      - appnet

  web:
    depends_on:
      - app
    image: nginx:alpine
    networks:
      - appnet
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./lumen:/lumen

  app:
    depends_on:
      - db
    build: ./php
    networks:
      - appnet
    volumes:
      - ./php/config:/usr/local/etc
      - ./php/supervisord.conf:/etc/supervisord.conf
      - ./lumen:/lumen

networks:
  appnet:
    driver: "bridge"
